# Generated by Django 4.2.3 on 2023-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_age_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('CAO', 'Центральный административный округ'), ('NAO', 'Северный административный округ'), ('NEAO', 'Северо-Восточный административный округ'), ('EAO', 'Восточный административный округ'), ('SEAO', 'Юго-Восточный административный округ'), ('SAO', 'Южный административный округ'), ('SWAO', 'Юго-Западный административный округ'), ('WAO', 'Западный административный округ'), ('NWAO', 'Северо-Западный административный округ')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
