# Generated by Django 4.2.3 on 2023-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_placemark_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemark',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='placemark',
            name='y',
            field=models.FloatField(),
        ),
    ]
