# Generated by Django 4.2.3 on 2023-08-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_review_reviewpictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='placemark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='map.placemark'),
        ),
        migrations.AlterField(
            model_name='reviewpictures',
            name='image',
            field=models.ImageField(upload_to='review_pictures/'),
        ),
        migrations.AlterField(
            model_name='reviewpictures',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='map.review'),
        ),
    ]
