# Generated by Django 4.2.3 on 2023-09-06 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('CAO', 'Центральный административный округ'), ('NAO', 'Северный административный округ'), ('NEAO', 'Северо-Восточный административный округ'), ('EAO', 'Восточный административный округ'), ('SEAO', 'Юго-Восточный административный округ'), ('SAO', 'Южный административный округ'), ('SWAO', 'Юго-Западный административный округ'), ('WAO', 'Западный административный округ'), ('NWAO', 'Северо-Западный административный округ')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
