# Generated by Django 4.2.3 on 2023-10-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_message_message_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
