# Generated by Django 4.2.3 on 2023-10-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_subscriptions_user_from_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('user_from', 'user_to')},
        ),
    ]
