# Generated by Django 4.2.3 on 2023-10-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscriptions_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_proposed',
            field=models.DateTimeField(null=True),
        ),
    ]
