# Generated by Django 4.2.3 on 2023-11-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referals_from', to=settings.AUTH_USER_MODEL)),
                ('invite_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referals_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
