# Generated by Django 4.2.3 on 2023-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemark',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
