# Generated by Django 4.2.3 on 2023-10-22 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_reviewpictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemark',
            name='name',
            field=models.CharField(default='hyeta', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placemark',
            name='time_from',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='placemark',
            name='time_to',
            field=models.TimeField(blank=True, default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='placemark',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placemark',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
