# Generated by Django 4.2.3 on 2023-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_placemark_name_placemark_time_from_placemark_time_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpictures',
            name='image',
            field=models.ImageField(null=True, upload_to='review_pictures/'),
        ),
    ]
