# Generated by Django 4.2.3 on 2023-10-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemark',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='placemark_main_images'),
        ),
    ]
