# Generated by Django 4.2.3 on 2023-10-30 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 30, 19, 57, 23, 582872, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='placemark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='map.placemark'),
        ),
    ]
