# Generated by Django 4.2.3 on 2023-11-05 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0015_complaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaint',
            new_name='Report',
        ),
    ]
