# Generated by Django 4.2.3 on 2023-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_rename_complaint_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='finished_early',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
