# Generated by Django 4.2.3 on 2023-08-19 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('CAO', 'Центральный административный округ'), ('NAO', 'Северный административный округ'), ('NEAO', 'Северо-Восточный административный округ'), ('EAO', 'Восточный административный округ'), ('SEAO', 'Юго-Восточный административный округ'), ('SAO', 'Южный административный округ'), ('SWAO', 'Юго-Западный административный округ'), ('WAO', 'Западный административный округ'), ('NWAO', 'Северо-Западный административный округ')], default=None, max_length=4)),
                ('height', models.PositiveSmallIntegerField(default=None)),
                ('age', models.PositiveSmallIntegerField(default=None)),
                ('weight', models.PositiveSmallIntegerField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
