name: Django CI

on:
  push:
    branches: [ "main", "experiments-with-ci/cd" ]
  pull_request:
    branches: [ "main", "experiments-with-ci/cd" ]

jobs:
  build:

    runs-on: [self-hosted, linux]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set SysVar
      run : |
        export $UNIFIEDBYFOOTBALL_EMAIL_LOGIN='unified_by_football@mail.ru'
        export $UNIFIEDBYFOOTBALL_EMAIL_PASSWORD='HG3dApPjBwb0WKnQ7nk4'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd source_code/
        python manage.py test
    - name: Build React
      run: |
        cd source_code/frontend/front-react/
        npm install
        CI=false npm run build
    - name: Start Django
      run: |
        cd source_code
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    
  
