name: Django CI

on:
  push:
    branches: [ "main", "experiments-with-ci/cd" ]
  pull_request:
    branches: [ "main", "experiments-with-ci/cd" ]

jobs:
  build:

    runs-on: [self-hosted]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        virtualenv venv
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd source_code/
        python3 manage.py test
    - name: Build React
      run: |
        cd source_code/frontend/front-react/
        npm install
        CI=false npm run build
    - name: Prepare Django
      run: |
        cd source_code
        python3 manage.py migrate
        python3 manage.py collectstatic
    - name: Start server side
      run: |
        cd source_code
        gunicorn -c config/gunicorn/dev.py
        systemctl restart nginx
    
  
